# Generated by Django 5.2.8 on 2025-11-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique_for_date='created', verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('new', 'новая'), ('in_progress', 'в процессе'), ('pending', 'ожидание'), ('blocked', 'заблокирована'), ('done', 'выполнена')], max_length=15, verbose_name='Статус задачи')),
                ('deadline', models.DateTimeField(verbose_name='Дата и время дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('categories', models.ManyToManyField(related_name='tasks', to='task_manager.category', verbose_name='Категория задачи')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название подзадачи')),
                ('description', models.TextField(verbose_name='Описание подзадачи')),
                ('status', models.CharField(choices=[('new', 'новая'), ('in_progress', 'в процессе'), ('pending', 'ожидание'), ('blocked', 'заблокирована'), ('done', 'выполнена')], max_length=20, verbose_name='Статус подзадачи')),
                ('deadline', models.DateTimeField(verbose_name='Дата и время дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtasks', to='task_manager.task', verbose_name='Основная задача')),
            ],
        ),
    ]
